name = "namespaced-fieldset-example"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

compatibility_date = "2022-04-16"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"
